### ISSUE TITLE
Code Issues: Incorrect Structure, Capitalization, Imports, and Variables in Automated_Mailing project

### ISSUE THREAD

**Issue by ChathuraAbeygunawardhana** [ndleah/python-mini-project#143]
### Description
The current code has several structural issues, including incorrect indentation, missing email and password values, and unnecessary variables.

### Type of issue
- [ ] Feature (New Script)
- [x] Bug
- [ ] Documentation

### Checklist:
- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### Description
The subject field should be capitalized as 'Subject' when setting it in the message. It is currently in lowercase as 'subject'.

### Type of issue
- [ ] Feature (New Script)
- [x] Bug
- [ ] Documentation

### Checklist:
- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### Description
The `name` module is imported from the `os` library (`from os import name`), but it is not used in the code. This import can be removed to improve code readability.

### Type of issue
- [ ] Feature (New Script)
- [x] Bug
- [ ] Documentation

### Checklist:
- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### Description
The lines for entering your email and password are indented incorrectly, making them part of the loop. These variables should be defined outside the loop as they are constant values.

### Type of issue
- [ ] Feature (New Script)
- [x] Bug
- [ ] Documentation

### Checklist:
- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### Description
There are unnecessary variables in the code. For instance, the `name` variable is assigned `data['name'].tolist()` but is not required as `name[i]` is used inside the loop.

### Type of issue
- [ ] Feature (New Script)
- [x] Bug
- [ ] Documentation

### Checklist:
- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

### Description
The code is missing the actual values for the `email` and `password` variables, making it impossible to run the script as intended.

### Type of issue
- [ ] Feature (New Script)
- [x] Bug
- [ ] Documentation

### Checklist:
- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by sidba2003** [comment]
Can you please specify the file paths for all of the mentioned bugs?
