### ISSUE TITLE
Which version of python does this repo use is it multiple or is it one???

### ISSUE THREAD

**Issue by 11aaditya11** [ndleah/python-mini-project#149]

**Comment by TERNION-1121** [comment]
I believe different projects written at different times may have different requirements. I'd suggest to go with the most recent Python3.11
That should make you able to run almost all the projects (bare speculation).

**Comment by emranpy** [comment]
above 3.x

**Comment by SureshRepos** [comment]
Python version doesn't matter as long as the required dependencies are included in requirements.txt and README.md file
