### ISSUE TITLE
Feature request: File and plaintext hashing

### ISSUE THREAD

**Issue by u749929** [ndleah/python-mini-project#165]
# Description

Hi, I would like to create a mini project to explore text and file hashes and demonstrate their functionality. I would like to have a built in program, where a user can input a string or file path and the program will return a corresponding hash value, as this would be useful to quickly compute hashes. 

I intend to use the hashlib library to achieve this. Could you please assign me to this issue and provide any feedback that you have on what you would like to see in the project.

Thanks.

## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by Yurnero-cyber** [comment]
Hi @u749929 ! There is no need to ask permission to create the mini project... the only things that needs attention is the [Code of Conduct](https://github.com/ndleah/python-mini-project/blob/main/CODE_OF_CONDUCT.md) and [How to contribute](https://github.com/ndleah/python-mini-project/blob/main/README.md). Don't forget to put a README file.

So just get to it!

Any doubts, feel free to ask here.

**Comment by Yurnero-cyber** [comment]
Hi @u749929 ! There is no need to ask permission to create the mini project... the only things that needs attention is the [Code of Conduct](https://github.com/ndleah/python-mini-project/blob/main/CODE_OF_CONDUCT.md) and [How to contribute](https://github.com/ndleah/python-mini-project/blob/main/README.md). Don't forget to put a README file.

So just get to it!

Any doubts, feel free to ask here.
