### ISSUE TITLE
Add Whatsapp Bot

### ISSUE THREAD

**Issue by sonustark1** [ndleah/python-mini-project#24]
# Description

Whatsapp Bot using pywhatkit Library in Python.

## Type of issue

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by AnishLohiya** [comment]
@ndleah Can I work on this Issue ?

**Comment by ndleah** [comment]
Hey @AnishLohiya,

Feel free to go ahead with this issue if you got the right solution 😄

**Comment by AnishLohiya** [comment]
> Hey @AnishLohiya,
> 
> Feel free to go ahead with this issue if you got the right solution 😄

![image](https://user-images.githubusercontent.com/87910771/147548135-a39db98c-d36a-4ef8-babc-e0736f5a242a.png)

Getting This Error while Trying to Clone the Repository. How can i resolve it ?
