### ISSUE TITLE
QR Code Generator

### ISSUE THREAD

**Issue by sonustark1** [ndleah/python-mini-project#27]
# Description

Add a New Python Project - QR Code Generator

## Type of issue

- [X] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by vivekthedev** [comment]
Project already merged https://github.com/ndleah/python-mini-project/pull/32#issue-1107003395
