### ISSUE TITLE
Add Project Whatsapp Bot in README.md

### ISSUE THREAD

**Issue by sonustark1** [ndleah/python-mini-project#35]
# Description

Project Whatsapp Bot Not added in README.md

## Type of issue

- [ ] Feature (New Script)
- [X] Bug
- [ ] Documentation

## Checklist:

- [X] I have read the project guidelines.
- [X] I have checked previous issues to avoid duplicates.
- [X] This issue will be meaningful for the project.

**Comment by zaydu98** [comment]
Solved and created PR!
