### ISSUE TITLE
Adding new features to already existing projects

### ISSUE THREAD

**Issue by 19lyaejin** [ndleah/python-mini-project#9]
# Description
First of all, thank you for merging my project before. I really appreciate it!

However,  I want to add some new features to already existing projects like Dice_Rolling_Simulator or Smart_Calculator project.
**_So, is it possible to add some new features to already existing projects?_**

Thank you and hope you have a wonderful weekend.

## Type of issue

- [x] Feature (New Script)
- [ ] Bug
- [ ] Documentation

## Checklist:

- [x] I have read the project guidelines.
- [x] I have checked previous issues to avoid duplicates.
- [x] This issue will be meaningful for the project.

**Comment by ndleah** [comment]
Hi @19lyaejin,

Yes, of course. Feel free to adjust these 2 current projects if you have any ideas for improvements.

Happy weekend!

**Comment by 19lyaejin** [comment]
Thank you:)
 I am really glad that I met this project as my first contribution to GitHub. Really, thanks a lot!
